### PR TITLE
Add empty default variable to prevent warnings

### PR DESCRIPTION
**Pull request by aba-rechsteiner**

### CODE REVIEW

**Comment by fraenki** [comment]
This would cause the following error...

```
Evaluation Error: Cannot reassign variable '$_hook_params_pre'
```

...because `$_hook_params_pre` is set a few lines later under certain conditions:

https://github.com/fraenki/puppet-acme/blob/eb6b8eae9ad31880313e7b74585f39de614675cd/manifests/request.pp#L112

If you could provide the warning that you are seeing I could probably provide a fix.

**Comment by fraenki** [comment]
@aba-rechsteiner Does https://github.com/fraenki/puppet-acme/commit/5792423b6357994cbf791e3d18ff2b06907398f5 fix your issue?

**Comment by fraenki** [comment]
My fix was released in 2.0.0. Please let me know if it does not fix your issue.

**Comment by aba-rechsteiner** [comment]
> @aba-rechsteiner Does [5792423](https://github.com/fraenki/puppet-acme/commit/5792423b6357994cbf791e3d18ff2b06907398f5) fix your issue?

sorry for the late feedback

after switch to 2.0.0 the cert was no longer deployed on the agent nodes. I'm back to 1.0.5 now, but I need to analyze this more closely

**Comment by fraenki** [comment]
@aba-rechsteiner Please open a new issue when you have analyzed the issue and please provide some details about your configuration.

**Comment by fraenki** [comment]
> after switch to 2.0.0 the cert was no longer deployed on the agent nodes

FYI, version 2.1.0 was released today and should fix this issue.

**Pull request closed without merging**
